[build]
builder = "nixpacks"

[deploy]
startCommand = "python src/railway_starter.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[http]
routes = [
    { path = "/ws/agent/.*", protocol = "websocket" }
] 